services:
  - type: worker
    name: affirmation-poster
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 generate_affirmation_video.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
    plan: free
    schedule: "0 6,8,10,12,14,16,18,20,22,0 * * *"  # Runs at 6am, 8am, 10am, 12pm, 2pm, 4pm, 6pm, 8pm, 10pm, 12am CST
    timezone: America/Chicago  # CST timezone 