services:
  - type: web
    name: affirmation-posting
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: FACEBOOK_ACCESS_TOKEN
        sync: false
      - key: INSTAGRAM_ACCOUNT_ID
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
      - key: AWS_REGION
        sync: false
      - key: GOOGLE_DRIVE_CREDENTIALS
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: FACEBOOK_PAGE_ID
        sync: false 