services:
  - type: worker
    name: affirmation-poster
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python3 generate_darkSunset_5sec.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
      - key: FACEBOOK_ACCESS_TOKEN
        sync: false
      - key: FACEBOOK_PAGE_ID
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
      - key: AWS_DEFAULT_REGION
        sync: false
    schedule: "0 18,20,22 * * *"  # Run at 6pm, 8pm, and 10pm CST
    timezone: America/Chicago  # CST timezone 