name: Daily Affirmation Posts

on:
  schedule:
    # Run at 6am, 8am, 10am, 12pm, 2pm, 4pm, 6pm, 8pm, 10pm, 12am UTC
    - cron: '0 6,8,10,12,14,16,18,20,22,0 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-and-post:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create output directory
        run: mkdir -p output
          
      - name: Run affirmation generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
          GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: python generate_affirmation_video.py
        
      - name: Upload output files
        uses: actions/upload-artifact@v3
        with:
          name: output-files
          path: output/
          retention-days: 7 